from modulefinder import packagePathMap
from tkinter import*
from tkinter import ttk
from PIL import Image,ImageTk  


class ChatBot:
    def __init__(self,root):
        self.root=root
        self.root.title("ChatBot")
        self.root.geometry("730x630+0+0")
        self.root.bind('<Return>',self.enter_func)
                             
        main_frame=Frame(self.root,bd=4,bg='powder blue',width=610)
        main_frame.pack()
        
        
        img_chat=Image.open('Images_GUI\chatbot.jpg')
        img_chat=img_chat.resize((200,70),Image.ANTIALIAS)
        self.photoimg=ImageTk.PhotoImage(img_chat)
                                    
        Title_label=Label(main_frame,bd=3,relief=RAISED,anchor='nw',width=730,compound=LEFT,image=self.photoimg,text='CHAT ME',font=('arial',30,'bold'),fg='green',bg='white')
        Title_label.pack(side=TOP)
    
        self.scroll_y=ttk.Scrollbar(main_frame,orient=VERTICAL)
        self.text=Text(main_frame,width=65,height=20,bd=3,relief=RAISED,font=('arial',14),yscrollcommand=self.scroll_y.set)   
        self.scroll_y.pack(side=RIGHT,fill=Y)
        self.text.pack()
            
        btn_frame=Frame(self.root,bd=4,bg='white',width=730)
        btn_frame.pack()
            
        label_1=Label(btn_frame,text="Type something",font=('arial',14,'bold'),fg='green',bg='white')
        label_1.grid(row=0,column=0,padx=5,sticky=W)
        
        self.entry=StringVar()
        self.entry1=ttk.Entry(btn_frame,textvariable=self.entry,width=30,font=('arial',17,'bold'))
        self.entry1.grid(row=0,column=1,padx=5,sticky=W)
        
        self.send=Button(btn_frame,text="send>>",command=self.send,font=('arial',16,'bold'),width=8,bg='green',)
        self.send.grid(row=0,column=2,padx=5,sticky=W)
    
        self.clare=Button(btn_frame,command=self.clear,text="Clear Data",font=('arial',15,'bold'),width=8,bg='red',fg='white')
        self.clare.grid(row=1,column=0,padx=5,sticky=W)
        
        self.msg=''
        self.label_11=Label(btn_frame,text=self.msg,font=('arial',14,'bold'),fg='red',bg='white')
        self.label_11.grid(row=1,column=1,padx=5,sticky=W)
        #========================Function Declaration===========================
    
    
    def enter_func(self,event):
        self.send.invoke()
        self.entry 
        
    def clear(self):
        self.text.delete('1.0',END)
        self.entry.set('')    
        
        
    def send(self):
        send='\t\t\t'+'You:'+self.entry.get()    
        self.text.insert(END,'\n'+send)
        if (self.entry.get()==''):
            self.msg='Please enter some input'
            self.label_11.config(text=self.msg,fg='red')
            
        else:
            self.msg=''
            self.label_11.config(text=self.msg,fg='red')
            
        if (self.entry.get()=='hello'):
            self.text.insert(END,'\n\n'+'Bot:Hi')
            
            
        elif (self.entry.get()=="hi"):
            self.text.insert(END,"\n\n"+"Bot:Hello")
            
        elif (self.entry.get()=="How are you?"):
            self.text.insert(END,"\n\n"+"Bot: fine and you")
            
        elif (self.entry.get()=="Fantastic"):
            self.text.insert(END,"\n\n"+"Bot: Nice To Hear")
            
        elif (self.entry.get()=="Who created you?"):
            self.text.insert(END,"\n\n"+"Bot: Vedika Created me using python")
            
        elif (self.entry.get()=="What is your name?"):
            self.text.insert(END,"\n\n"+"Bot: My name is Mr. Hacker")
            
        elif (self.entry.get()=="Can you speak Marathi"):
            self.text.insert(END,"\n\n"+"Bot: I'm still learning it..")
                                                            
        elif (self.entry.get()=="What is machine learning?"):
           
            self.text.insert(END,"\n\n"+"Bot: Machine learning is a branch of artificial intelligence (AI) and computer science which focuses on the use of data and algorithms to imitate the way that humans learn, gradually improving its accuracy. ") 
        
        elif (self.entry.get()=="How does face recognition work?"):
              
             self.text.insert(END,"\n\n"+"Bot: Facial recognition uses computer-generated filters to transform face images into numerical expressions that can be compared to determine their similarity. These filters are usually generated by using deep “learning,” which uses artificial neural networks to process data.")          
    
        elif (self.entry.get()=="How does facial recognition work step by step?"):
            self.text.insert(END,"\n\n"+"Bot: Step 1: Face detection:The camera detects and locates the image of a face, either alone or in a crowd. The image may show the person looking straight ahead or in profile. \nStep 2: Face analysis: Next, an image of the face is captured and analyzed. Most facial recognition technology relies on 2D rather than 3D images because it can more conveniently match a 2D image with public photos or those in a database.Step 3: Converting the image to data :The face capture process transforms analog information (a face) into a set of digital information (data) based on the person's facial features. Your face's analysis is essentially turned into a mathematical formula.Step 4: Finding a match :Your faceprint is then compared against a database of other known faces. ")

        elif (self.entry.get()=="How many countries use facial recognition?"):
            self.text.insert(END,"\n\n"+"Bot: In use  98\nApproved, but not implemented 12\nConsidering facial recognotion")
        
        elif (self.entry.get()=="What is python programing?"):
            self.text.insert(END,"\n\n"+"Bot:Python is a general purpose\nand high level orogramming language.\nYou can use Python")
                             
                             
        elif (self.entry.get()=="What is chatbot?"):
                             
            self.text.insert(END,"\n\n"+"Bot:A chatbot is a computer \nprogram that's designed to \nsimulate human conversation.")
        
        elif (self.entry.get()=="bye"):
            self.text.insert(END,"\n\n"+"Bot:Thank You for chatting")
        
        
            
            
        else:
             self.text.insert(END,"\n\n"+"Bot:Sorry I didn't get it")    
                             
                             
                             
if __name__ == "__main__":
    root=Tk()
    obj=ChatBot(root)
    root.mainloop()